services:
  frontend:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:3000/api/v1
      - NEXT_PUBLIC_WS_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - gerensee

  backend:
    image: gerensee-backend:latest
    ports:
      - "3000:3000"
    networks:
      - gerensee

networks:
  gerensee:
    driver: bridge
